### PR TITLE
Seed file complete

### PR DESCRIPTION
**Pull request by Teleri**
Seed file should be used on creating/migrating a new DB

Read the comments in the seed file for instruction

### CODE REVIEW

**Review by mberthier — APPROVED** [review]

**Comment by mberthier** [comment]
You should just delete all instances in the Seed. 

User.delete_all...

**Comment by Teleri** [comment]
Fair point 😄

**Comment by mberthier** [comment]
We should also add a planet image for all planets in the seed, now that the image column has been added.

**Comment by Teleri** [comment]
OK I will add that

**Pull request merged**
